---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chtUserManagement.fullname" . }}
  namespace: {{ include "chtUserManagement.namespace" . }}
type: Opaque
data:
  COOKIE_PRIVATE_KEY: {{ include "chtUserManagement.COOKIE_PRIVATE_KEY" . }}
