---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chtUserManagement.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  COOKIE_PRIVATE_KEY: {{ include "chtUserManagement.COOKIE_PRIVATE_KEY" . }}
