---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "observability.serviceAccountName" . }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: true
