---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability.fullname" . }}-vector
  labels:
    {{- include "observability.labels" . | nindent 4 }}
data:
  vector.yaml: |
{{ tpl (toYaml .Values.vector.customConfig) . | indent 4 }}
