{{- if .Values.grafana.auth.github.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: observability-grafana-oauth-github
type: Opaque
stringData:
  client_id: {{ .Values.grafana.auth.github.client_id }}
  client_secret: {{ .Values.grafana.auth.github.client_secret }}
{{- end }}
