{{- if .Values.grafana.auth.google.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: observability-grafana-oauth-google
type: Opaque
stringData:
  client_id: {{ .Values.grafana.auth.google.client_id }}
  client_secret: {{ .Values.grafana.auth.google.client_secret }}
{{- end }}
