apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-datasources" (include "observability.fullname" $) | trunc 63 | trimSuffix "-" }}
  labels:
    grafana_datasource: 'medic-observability'
stringData:
  medic-datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Medic / Loki
        type: loki
        access: proxy
        url: http://loki-gateway:80
        editable: false
      - name: Medic / Prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "observability.prometheus.fullname" . }}:80
        editable: false
      - name: Medic / Tempo
        type: tempo
        access: proxy
        url: http://tempo-query-frontend:3100
        editable: false
