apiVersion: v2
name: observability
description: A Helm chart for medic observability
home: https://github.com/medic/helm-charts/tree/main/charts/observability
icon: https://avatars.githubusercontent.com/u/474424?s=200&v=4

type: application

version: 0.1.4

appVersion: ""
dependencies:
  - name: grafana
    version: "7.3.*"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: loki
    version: "5.36.*"
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: opencost
    version: "1.33.*"
    repository: https://opencost.github.io/opencost-helm-chart
    condition: opencost.enabled
  - name: prometheus
    version: "25.19.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
