apiVersion: v2
name: base-single-app
description: Single app helm chart to simplify configuration
home: https://github.com/medic/helm-charts/tree/gh-pages
icon: https://avatars.githubusercontent.com/u/474424?s=200&v=4

type: library

version: 0.2.1

appVersion: ""
