{{- if eq .Values.cluster_type "gke" }}
apiVersion: v1
kind: Service
metadata:
  name: api-ingress-ip
  labels:
    {{- include "cht-chart-4x.gcp.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
{{- end }}
