apiVersion: v2
name: cht-user-management
description: Chart for cht-user-management
home: https://github.com/medic/cht-user-management
icon: https://avatars.githubusercontent.com/u/474424?s=200&v=4

type: application

version: 0.2.1

dependencies:
  - alias: cht-user-management
    name: base-single-app
    version: "0.2.0"
    repository: https://docs.communityhealthtoolkit.org/helm-charts
    # repository: file://../base-single-app

appVersion: ""
