cht-user-management:
  replicaCount: 1

  service:
    port: 3000

  image:
    repository: public.ecr.aws/medic/cht-user-management

  # env:
  #   CONFIG_NAME: changeme

  envSecrets:
    - env: COOKIE_PRIVATE_KEY
      secretName: '{{ include "chtUserManagement.fullname" . }}'
