apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cht.service: api
  name: cht-api
spec:
  replicas: 1
  selector:
    matchLabels:
      cht.service: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        cht.service: api
    spec:
      containers:
        - env:
            - name: BUILDS_URL
              value: {{ .Values.upstream_servers.builds_url }}
            - name: COUCH_URL
              value: >
                {{- if .Values.couchdb.useExternal -}}
                http://{{ .Values.couchdb.external.username }}:{{ .Values.couchdb.external.password }}@{{ .Values.couchdb.external.host }}:{{ .Values.couchdb.external.port }}/medic
                {{- else -}}
                http://{{ .Values.couchdb.user }}:{{ .Values.couchdb.password }}@haproxy.{{ .Values.namespace }}.svc.cluster.local:5984/medic
                {{- end }}
            - name: UPGRADE_SERVICE_URL
              value: http://upgrade-service.{{ .Values.namespace }}.svc.cluster.local:5008
            - name: API_PORT
              value: '5988'
          image: {{ .Values.upstream_servers.docker_registry }}/cht-api:{{ .Values.cht_image_tag }}
          {{- if eq .Values.cache_images false }}
          imagePullPolicy: Always
          {{- end }}
          name: cht-api
          ports:
            - containerPort: 5988
          resources: {}
      restartPolicy: Always
status: {}
