{{- if and (eq (toString .Values.couchdb.clusteredCouch_enabled) "false") (or (eq (toString .Values.cluster_type) "eks") (eq (toString .Values.cluster_type) "gke")) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cht.service: couchdb-claim0
  name: couchdb-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.couchdb.couchdb_node_storage_size }}
  {{- if eq (toString .Values.cluster_type) "eks" }}
    {{- if eq (toString .Values.couchdb_data.preExistingDataAvailable) "true" }}
  volumeName: couchdb-pv-{{ .Values.namespace }}
  storageClassName: ""
    {{- else }}
  storageClassName: ebs-gp2
    {{- end }}
  {{- else if eq (toString .Values.cluster_type) "gke" }}
    {{- if eq (toString .Values.couchdb_data.preExistingDataAvailable) "true" }}
  volumeName: couchdb-pv-{{ .Values.namespace }}
  storageClassName: ""
    {{- else }}
  storageClassName: standard-rwo
    {{- end }}
  {{- end }}
status: {}
{{- end }}
