apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cht.service: sentinel
  name: cht-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      cht.service: sentinel
  strategy: {}
  template:
    metadata:
      labels:
        cht.service: sentinel
    spec:
      containers:
        - env:
            - name: API_HOST
              value: api.{{ .Values.namespace }}.svc.cluster.local
            - name: COUCH_URL
              value: >
                {{- if .Values.couchdb.useExternal -}}
                http://{{ .Values.couchdb.external.username }}:{{ .Values.couchdb.external.password }}@{{ .Values.couchdb.external.host }}:{{ .Values.couchdb.external.port }}/medic
                {{- else -}}
                http://{{ .Values.couchdb.user }}:{{ .Values.couchdb.password }}@haproxy.{{ .Values.namespace }}.svc.cluster.local:5984/medic
                {{- end }}
            - name: API_PORT
              value: '5988'
          image: {{ .Values.upstream_servers.docker_registry }}/cht-sentinel:{{ .Values.cht_image_tag }}
          {{- if eq .Values.cache_images false }}
          imagePullPolicy: Always
          {{- end }}
          name: cht-sentinel
          resources: {}
      restartPolicy: Always
status: {}
